name: Lint
description: Run linting checks

inputs:
  paths:
    description: Paths to lint
    default: .
  config:
    description: Lint config file
    default: .eslintrc

runs:
  using: composite
  steps:
    - shell: bash
      run: "node ${{ github.action_path }}/scripts/lint.cli.mjs --paths='${{ inputs.paths }}' --config='${{ inputs.config }}'"
