name: Lint
description: Run linting checks

inputs:
  paths:
    description: Paths to lint
    default: .
  config:
    description: Lint config file
    default: .eslintrc

runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: bazelisk run //actions/lint --
        --paths='${{ inputs.paths }}'
        --config='${{ inputs.config }}'
