name: Debug
description: Print the full file tree from $HOME

runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: "bazelisk run //actions/debug --"
