name: Shared Workflow

on:
  workflow_call:
    inputs:
      project-name:
        type: string
        default: my-project

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: stefanpenner/shared-workflow-test
          ref: ${{ github.job_workflow_sha }}
          path: _self
          # Optional: only fetch the actions/ directory
          sparse-checkout: actions
          sparse-checkout-cone-mode: true

      - uses: ./_self/actions/setup
        with:
          project-name: ${{ inputs.project-name }}

      - uses: ./_self/actions/lint
      - uses: ./_self/actions/test
        with:
          suite: integration
