name: Shared Workflow

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      project-name:
        type: string
        default: my-project

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Exclude shared actions from git
        run: mkdir -p .git/info && echo '.github/_shared-workflow/' >> .git/info/exclude

      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          repository: stefanpenner/shared-workflow-test
          ref: ${{ inputs.ref }}
          path: .github/_shared-workflow

      - name: Debug
        uses: ./.github/_shared-workflow/actions/debug

      - name: Setup
        uses: ./.github/_shared-workflow/actions/setup
        with:
          project-name: ${{ inputs.project-name }}

      - name: Lint
        uses: ./.github/_shared-workflow/actions/lint
      - name: Test
        uses: ./.github/_shared-workflow/actions/test
        with:
          suite: integration
