name: Test No Token

on:
  workflow_call:

jobs:
  no-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: stefanpenner/shared-workflow-test
          ref: ${{ github.job_workflow_sha }}
          path: _self
          token: ""

      - uses: ./_self/actions/setup
        with:
          project-name: no-token-test
